const quotes = [
  { quote: "Chess is the struggle against the error.", author: "Johannes Zukertort" },
  { quote: "Every chess master was once a beginner.", author: "Irving Chernev" },
  { quote: "Avoid the crowd. Do your own thinking independently. Be the chess player, not the chess piece.", author: "Ralph Charell" },
  { quote: "Chess holds its master in its own bonds, shackling the mind and brain so that the inner freedom of the very strongest must suffer.", author: "Albert Einstein" },
  { quote: "Chess is a war over the board. The object is to crush the opponent's mind.", author: "Bobby Fischer" },
  { quote: "Chess is the gymnasium of the mind.", author: "Blaise Pascal" },
  { quote: "Even the laziest King flees wildly in the face of a double check!", author: "Aaron Nimzowitsch" },
  { quote: "We cannot resist the fascination of sacrifice, since a passion for sacrifices is part of a Chess player's nature.", author: "Rudolf Spielman" },
  { quote: "Nothing excites jaded Grandmasters more than a theoretical novelty.", author: "Dominic Lawson" },
  { quote: "A win by an unsound combination, however showy, fills me with artistic horror.", author: "Wilhelm Steinitz" },
  { quote: "Only the player with the initiative has the right to attack.", author: "Wilhelm Steinitz" },
  { quote: "Chess is rarely a game of ideal moves. Almost always, a player faces a series of difficult consequences whichever move he makes.", author: "David Shenk" },
  { quote: "When you see a good move, look for a better one.", author: "Emanuel Lasker" },
  { quote: "Half the variations which are calculated in a tournament game turn out to be completely superfluous. Unfortunately, no one knows in advance which half.", author: "Jan Timman" },
  { quote: "Even a poor plan is better than no plan at all.", author: "Mikhail Chigorin" },
  { quote: "Tactics is knowing what to do when there is something to do; strategy is knowing what to do when there is nothing to do.", author: "Savielly Tartakower" },
  { quote: "In life, as in chess, forethought wins.", author: "Charles Buxton" },
  { quote: "You may learn much more from a game you lose than from a game you win. You will have to lose hundreds of games before becoming a good player.", author: "José Raúl Capablanca" },
  { quote: "I don't believe in psychology. I believe in good moves.", author: "Bobby Fischer" },
  { quote: "Play the opening like a book, the middlegame like a magician, and the endgame like a machine.", author: "Rudolph Spielmann" },
  { quote: "I used to attack because it was the only thing I knew. Now I attack because I know it works best.", author: "Garry Kasparov" },
  { quote: "It's always better to sacrifice your opponent's men.", author: "Savielly Tartakower" },
  { quote: "One doesn't have to play well, it's enough to play better than your opponent.", author: "Siegbert Tarrasch" },
  { quote: "Up to this point, White has been following well-known analysis. But now he makes a fatal error: he begins to use his own head.", author: "Siegbert Tarrasch" },
  { quote: "Of chess, it has been said that life is not long enough for it, but that is the fault of life, not chess.", author: "William Napier" },
  { quote: "Chess is beautiful enough to waste your life for.", author: "Hans Ree" },
  { quote: "A chess game in progress is… a cosmos unto itself, fully insulated from an infant's cry, an erotic invitation, or war.", author: "David Shenk" },
  { quote: "It will be cheering to know that many people are skillful chess players, though in many instances their brains, in a general way, compare unfavorably with the cognitive faculties of a rabbit.", author: "James Mortimer" },
  { quote: "The pin is mightier than the sword.", author: "Fred Reinfeld" },
  { quote: "The only thing chess players have in common is chess.", author: "Lodewijk Prins" },
  { quote: "Those who say they understand chess, understand nothing.", author: "Robert Hübner" },
  { quote: "One bad move nullifies forty good ones.", author: "Bernhard Horwitz" },
  { quote: "If your opponent offers you a draw, try to work out why he thinks he's worse off.", author: "Nigel Short" },
  { quote: "Your body has to be in top condition. Your chess deteriorates as your body does. You can't separate body and mind.", author: "Bobby Fischer" },
  { quote: "A good player is always lucky.", author: "José Raúl Capablanca" },
  { quote: "The hardest game to win is a won game.", author: "Emanuel Lasker" },
  { quote: "Chess is not for timid souls.", author: "Wilhelm Steinitz" },
  { quote: "Chess is a curse upon a man.", author: "H. G. Wells" },
  { quote: "Chess is so inspiring that I do not believe a good player is capable of having an evil thought during the game.", author: "Wilhelm Steinitz" },
  { quote: "He who fears an isolated Queen's Pawn should give up Chess.", author: "Siegbert Tarrasch" },
  { quote: "It doesn't matter how strong a player you are, if you fail to register some development in the opening, then you are asking for trouble.", author: "John Emms" },
  { quote: "When having an edge, [Anatoly] Karpov often marked time and still gained the advantage! I don't know anyone else who could do that, it's incredible.", author: "Vladimir Kramnik" },
  { quote: "Chess is a forcing house where the fruits of character can ripen more fully than in life.", author: "Edward Morgan Forster" },
  { quote: "A king may be the most important piece on the chessboard; however, the queen is the most powerful.", author: "Karim R. Ellis" },
  { quote: "To venture an opinion is like moving a piece at chess: it may be taken, but it forms the beginning of a game that is won.", author: "Johann Wolfgang von Goethe" },
  { quote: "It is no easy matter to reply correctly to [Emanuel] Lasker's bad moves.", author: "W.H.K. Pollock" },
  { quote: "For in the idea of chess and the development of the chess mind we have a picture of the intellectual struggle of mankind.", author: "Richard Réti" },
  { quote: "Chess, like love, is infectious at any age.", author: "Salo Flohr" },
  { quote: "Chess is played with the mind and not with the hands!", author: "Renaud and Kahn" },
  { quote: "In Chess, just as in life, today's bliss may be tomorrow's poison.", author: "Assaic" },
  { quote: "Chess is a fairy tale of 1001 blunders.", author: "Savielly Tartakower" },
  { quote: "I started by just sitting by the chessboard exploring things. I didn't even have books at first, and I just played by myself. I learnt a lot from that, and I feel that it is a big reason why I now have a good intuitive understanding of chess.", author: "Magnus Carlsen" },
  { quote: "I don't know whether computers are improving the style of play, I know they are changing it. Chess has become a different game, one could say that computers have changed the world of chess. That is pretty clear.", author: "Vladimir Kramnik" },
  { quote: "I think up my own moves, and I make my opponent think up his.", author: "Alexander Alekhine" },
  { quote: "Help your pieces so they can help you.", author: "Paul Morphy" },
  { quote: "The shortcoming of hanging pawns is that they present a convenient target for attack. As the exchange of men proceeds, their potential strength lessens and during the endgame they turn out, as a rule, to be weak.", author: "Boris Spassky" },
  { quote: "Chess is a very logical game and it is the man who can reason most logically and profoundly in it that ought to win.", author: "José Raúl Capablanca" },
  { quote: "After a bad opening, there is hope for the middle game. After a bad middle game, there is hope for the endgame. But once you are in the endgame, the moment of truth has arrived.", author: "Edmar Mednis" },
  { quote: "Chess is the art of analysis.", author: "Mikhail Botvinnik" },
  { quote: "When in doubt — play chess.", author: "Walter Tevis" },
  { quote: "Life is too short for chess.", author: "Lord Byron" },
  { quote: "The older I grow, the more I value pawns.", author: "Paul Keres" },
  { quote: "Pawn endings are to chess what putting is to golf.", author: "C.J.S. Purdy" },
  { quote: "Some part of a mistake is always correct.", author: "Savielly Tartakower" },
  { quote: "All chess masters can play one game blindfolded.", author: "George Koltanowski" },
  { quote: "Morphy was probably the greatest genius of them all.", author: "Bobby Fischer" },
  { quote: "There are two types of sacrifices: correct ones and mine.", author: "Mikhail Tal" },
  { quote: "The blunders are all there on the board, waiting to be made.", author: "Savielly Tartakower" },
  { quote: "On the chess-board lies and hypocrisy do not survive long.", author: "Emanuel Lasker" },
  { quote: "To avoid losing a piece, many a person has lost the game.", author: "Savielly Tartakower" },
  { quote: "The first principle of attack: don't let the opponent develop!", author: "Reuben Fine" },
  { quote: "Chess is mental torture.", author: "Garry Kasparov" },
  { quote: "The loser is always at fault.", author: "Vasily Panov" },
  { quote: "I hate anyone who beats me.", author: "Lisa Lane" },
  { quote: "Chess was Capablanca's mother tongue.", author: "Richard Réti" },
  { quote: "Let the perfectionist play postal.", author: "Yasser Seirawan" },
  { quote: "There are no heroes in chess.", author: "Cory Evans" },
  { quote: "If drink is the curse of the working classes and work is the curse of the drinking classes, then chess is the curse of the thinking classes.", author: "J. Ross" },
  { quote: "I'd rather have a pawn than a finger.", author: "Reuben Fine" },
  { quote: "A wood-pusher overlooks the ranks.", author: "Russian saying" },
  { quote: "There just isn't enough televised chess.", author: "David Letterman" },
  { quote: "There is no remorse like the remorse of chess.", author: "H. G. Wells" },
  { quote: "When the going gets tactical, the computers get going.", author: "Robert Hyatt" },
  { quote: "No price is too great for the scalp of the enemy king.", author: "Alexander Koblents" },
  { quote: "You cannot play chess if you are kind-hearted.", author: "French proverb" },
  { quote: "An isolated pawn spreads gloom all over the chessboard.", author: "Savielly Tartakower" },
  { quote: "Creating an undesired stalemate is the height of stupidity.", author: "Anonymous" },
  { quote: "Chess is 99% tactics.", author: "Richard Teichmann" },
  { quote: "A good sacrifice is one that is not necessarily sound but leaves your opponent dazed and confused.", author: "Rudolf Spielmann" },
  { quote: "Modern chess is too much concerned with things like pawn structure. Forget it—checkmate ends the game.", author: "Nigel Short" },
  { quote: "Only a good bishop can be sacrificed; a bad bishop can only be lost.", author: "Yuri Razuvaev" },
  { quote: "The great master places a knight at e5; mate follows by itself.", author: "Savielly Tartakower" },
  { quote: "Some knights don't leap—they limp.", author: "Savielly Tartakower" },
  { quote: "A chess game is divided into three stages: the first, when you hope you have the advantage; the second, when you believe you have an advantage; and the third, when you know you're going to lose!", author: "Savielly Tartakower" },
  { quote: "Black is in desperate need of a good idea—or, in standard chess notation, +−.", author: "Mark Dvoretsky and Artur Yusupov" },
  { quote: "It is not a move, even the best move, that you must seek, but a realizable plan.", author: "Eugene Znosko-Borovsky" },
  { quote: "A draw can be obtained normally by repeating three moves, but also by one bad move.", author: "Savielly Tartakower" },
  { quote: "The winner of the game is the player who makes the next-to-last mistake.", author: "Savielly Tartakower" },
  { quote: "Those chess lovers who ask me how many moves I usually calculate in advance, when making a combination, are always astonished when I reply, quite truthfully, 'As a rule, not a single one.'", author: "Richard Réti" },
  { quote: "I wasn't sure what square to take the rook to. Because there were three alternatives, I decided to go for the middle one.", author: "Jan Timman" },
  { quote: "The idea comes before the logical argument.", author: "Gerald Abrahams" },
  { quote: "Good positions don't win games; good moves do.", author: "Gerald Abrahams" },
  { quote: "I've wasted a Black.", author: "Gerald Abrahams" },
  { quote: "You can retreat pieces, but not pawns. So always think twice about pawn moves.", author: "Michael Stean" },
  { quote: "Open files can be used by both players. The chess player, not being an unselfish advocate of equal opportunity, naturally prefers a one-way system.", author: "Michael Stean" },
  { quote: "Chess is above all a fight.", author: "Emanuel Lasker" },
  { quote: "During a chess competition, a chess master should be a combination of a beast of prey and a monk.", author: "Alexander Alekhine" },
  { quote: "Before the endgame, the gods have placed the middlegame.", author: "Siegbert Tarrasch" },
  { quote: "If you have any doubt what to study, study endgames. Openings teach you openings; endings teach you chess.", author: "Stephan Gerzadowicz" },
  { quote: "Tonight I am playing against the black pieces.", author: "Akiba Rubinstein" },
  { quote: "I just think we should look at this as a chess match between the world's greatest chess player and Garry Kasparov.", author: "Louis Gerstner" },
  { quote: "Excellence at chess is one mark of a scheming mind.", author: "Arthur Conan Doyle" },
  { quote: "Style, I've got no style.", author: "Anatoly Karpov" },
  { quote: "Tal doesn't move the pieces by hand; he uses a magic wand.", author: "Viacheslav Ragozin" },
  { quote: "Fischer almost never has any bad pieces. He exchanges them, and the bad pieces remain with his opponents.", author: "Yuri Balashov" },
  { quote: "Winning isn't everything, but losing is nothing.", author: "Edmar Mednis" },
  { quote: "In chess, at least, the brave inherit the earth.", author: "Edmar Mednis" },
  { quote: "Later, I began to succeed in decisive games. Perhaps because I realized a very simple truth: not only was I worried, but also my opponent.", author: "Mikhail Tal" },
  { quote: "No fool can play chess, and only fools do.", author: "German proverb" },
  { quote: "You may knock your opponent down with the chessboard, but that does not prove that you are the better player.", author: "English proverb" },
  { quote: "The captain was a good chess player, and the games with him were always interesting. Yossarian had stopped playing chess with him because the games were so interesting that they were foolish.", author: "Joseph Heller" },
  { quote: "The initial position is decisive zugzwang.", author: "Jon Speelman" },
  { quote: "After 1. e4, White's game is in its last throes!", author: "Gyula Breyer" },
  { quote: "When I'm White, I win because I am White. When I'm Black, I win because I am Bogoljubow.", author: "Efim Bogoljubow" },
  { quote: "I have never in my life played the French Defence, which is the dullest of all openings.", author: "Wilhelm Steinitz" },
  { quote: "I don't know what I am going to play, so how can she know what I am going to play?", author: "Arthur Bisguier" },
  { quote: "There are two classes of men: those who are content to yield to circumstances and who play whist; those who aim to control circumstances, and who play chess.", author: "Mortimer Collins" },
]

export default quotes
